version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: npm test
  hithere: 
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Hello!"
workflows:
  version: 2
  Build_Test_Lint:
    jobs: 
      - build
      - hithere
      - test:
          requires: 
            - hithere